name: genome-jigsaw
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Python environment
  - python=3.9
  - pip
  
  # Quality Control
  - fastqc=0.12.1
  
  # Data Cleaning
  - fastp=0.23.4
  
  # Genome Assembly
  - spades=3.15.5
  
  # Genome Annotation
  - prokka=1.14.6
  
  # Pan-genome Analysis
  - roary=3.13.0
  
  # Multiple Sequence Alignment
  - mafft=7.520
  
  # Phylogenetic Tree Construction
  - iqtree=2.2.2.6
  
  # Gene Screening
  - abricate=1.0.1
  
  # Additional utilities
  - multiqc=1.14
  - seqtk=1.3
  - samtools=1.17
  - bcftools=1.17
  - bedtools=2.31.0
  - parallel=20230722
  
  # Data processing and visualization
  - pandas=2.0.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - biopython=1.81
  
  # System utilities
  - wget=1.21.4
  - curl=8.2.1
  - unzip=6.0
  - gzip=1.12
  
  # Perl dependencies for some tools
  - perl=5.32.1
  - perl-bioperl=1.7.8
  - perl-xml-simple=2.25
  
  # R and packages for downstream analysis
  - r-base=4.3.1
  - r-ggplot2=3.4.3
  - r-dplyr=1.1.2
  - r-phytools=1.5_1
  - r-ape=5.7_1
  
  # Additional bioinformatics tools
  - blast=2.14.1
  - hmmer=3.3.2
  - prodigal=2.6.3
  
  # Pip packages
  - pip:
    - biopandas==0.4.1
    - dendropy==4.6.1
    - ete3==3.1.3